# This workflow will run unit tests using Gradle when a Pull Request is opened against "master" branch

name: Gradle Unit Tests

on:
  pull_request:
      brances: [master]

jobs:
  build:

      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: 1.8

      - name: Clean
        run: ./gradlew clean
      - name: Build with Gradle
        run: ./gradlew build
      - name: All Platform Tests
        run: ./gradlew check
